services:
  
  gamerspotbackend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"

  gamerspotfrontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"