FROM node:16 as backend-build
WORKDIR /backend
COPY /backend/package.json /backend/package.json
COPY /backend/app.js /backend/app.js
COPY /backend/data /backend/data
COPY /backend/routes /backend/routes
COPY /backend/utils /backend/utils
RUN npm install && npm run build
EXPOSE 4000 

FROM node:16
WORKDIR /root/
COPY --from=backend-build /backend/dist .

# CMD ["npm", "start"]