FROM node:16 as frontend-build
WORKDIR /frontend
COPY /frontend/package.json /frontend/package.json
COPY /frontend/public /frontend/public
COPY /frontend/src /frontend/src
RUN npm install && npm run build
EXPOSE 3000

FROM node:16
WORKDIR /root/
COPY --from=frontend-build /frontend/build ./frontend/build
# CMD ["npm", "start"]