FROM node:16
WORKDIR /backend
COPY /backend/package.json /backend/package.json
COPY /backend/app.js /backend/app.js
COPY /backend/data /backend/data
COPY /backend/routes /backend/routes
COPY /backend/utils /backend/utils
RUN npm install
EXPOSE 4000 
CMD ["npm", "start"]