name: Docker Image CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      # - name: Run Docker build
      #   run: docker build -f Dockerfile -t gamer-spot-image .

      # - name: Run Docker container
      #   run: docker run -d -p 4000:4000 --name gamer-spot gamer-spot-image

      # - run: docker build . -f ./Dockerfile.backend -t gamerspot-be:1
      # - run: docker build . -f ./Dockerfile.frontend -t gamerspot-fe:1

      # - name: Docker Compose 
      #   uses: isbang/compose-action@v1.4.1
        
      # -
      #   name: Get timestamp
      #   uses: gerred/actions/current-time@master
      #   id: current-time

      # - name: Run string replace
      #   uses: frabert/replace-string-action@master
      #   id: format-time
      #   with:
      #     pattern: '[:\.]+'
      #     string: "${{ steps.current-time.outputs.time }}"
      #     replace-with: '-'
      #     flags: 'g'
     
      # - run: ls
      # - name: Generate deployment package
      #   run: zip -r deploy.zip *

      # - name: Deploy to Elastic Beanstalk
      #   uses: einaregilsson/beanstalk-deploy@v14
      #   with: 
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: gamer-spot-application
      #     environment_name: gamer-spot-env
      #     version_label: "gamer-spot-application-${{ steps.format-time.outputs.replaced }}"
      #     region: us-east-1
      #     deployment_package: deploy.zip
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: Dockerfile
          push: true
          tags: gamer-spot-application:latest

# .github/workflows/main.yml continued

      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: <beanstalk application name>
          environment_name: <beanstalk environment name>
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-west-2
          deployment_package: deploy.zip
